version: '3'

services:
  curso:
    build: ./curso
    depends_on:
      - datacurso
    environment:
      - PORT=3000
      - MONGODB_CNN=mongodb://datacurso:27017/test
    # ports:
    #   - "2500:2500"
  aspirante:
    build: ./aspirante
    depends_on:
      - dataaspirante
    environment:
      - PORT=3000
      - MONGODB_CNN=mongodb://dataaspirante:27017/test
  inscripcion:
      build: ./inscripcion
      depends_on:
        - datainscripcion
      environment:
        - PORT=3000
        - MONGODB_CNN=mongodb://datainscripcion:27017/test
  datacurso:
    image: mongo
    # ports:
    #   - "27017:27017"
  dataaspirante:
    image: mongo
    # ports:
    #   - "27017:27017"
  datainscripcion:
    image: mongo
    # ports:
    #   - "27017:27017"
  nginx:
    image: nginx:latest
    ports:
      - "8888:8080"
      ## Cambie de puerto al 8888:8080 por que en mi compu me daba error
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - curso
      - aspirante
      - inscripcion
